//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBEncapsulation
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using DbContextExtension;
    using DistributionModel;
    using DistributionModel.Finance;
    using SysProcessModel;
    
    public partial class DistributionEntities : AdapDbContext
    {
        public DistributionEntities()
            : base("DistributionConstr", "res://*/Distribution.csdl|res://*/Distribution.ssdl|res://*/Distribution.msl")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BillAllocate> BillAllocate { get; set; }
        public DbSet<BillAllocateDetails> BillAllocateDetails { get; set; }
        public DbSet<BillCannibalize> BillCannibalize { get; set; }
        public DbSet<BillCannibalizeDetails> BillCannibalizeDetails { get; set; }
        public DbSet<BillDelivery> BillDelivery { get; set; }
        public DbSet<BillDeliveryDetails> BillDeliveryDetails { get; set; }
        public DbSet<BillGoodReturn> BillGoodReturn { get; set; }
        public DbSet<BillGoodReturnDetails> BillGoodReturnDetails { get; set; }
        public DbSet<BillOrder> BillOrder { get; set; }
        public DbSet<BillOrderChange> BillOrderChange { get; set; }
        public DbSet<BillOrderDetails> BillOrderDetails { get; set; }
        public DbSet<BillRetail> BillRetail { get; set; }
        public DbSet<BillRetailDetails> BillRetailDetails { get; set; }
        public DbSet<BillSnapshot> BillSnapshot { get; set; }
        public DbSet<BillSnapshotDetailsWithUniqueCode> BillSnapshotDetailsWithUniqueCode { get; set; }
        public DbSet<BillStocktake> BillStocktake { get; set; }
        public DbSet<BillStocktakeContrast> BillStocktakeContrast { get; set; }
        public DbSet<BillStocktakeContrastDetails> BillStocktakeContrastDetails { get; set; }
        public DbSet<BillStocktakeDetails> BillStocktakeDetails { get; set; }
        public DbSet<BillStoreMove> BillStoreMove { get; set; }
        public DbSet<BillStoreMoveDetails> BillStoreMoveDetails { get; set; }
        public DbSet<BillStoreOut> BillStoreOut { get; set; }
        public DbSet<BillStoreOutDetails> BillStoreOutDetails { get; set; }
        public DbSet<BillStoring> BillStoring { get; set; }
        public DbSet<OrganizationAllocationGrade> OrganizationAllocationGrade { get; set; }
        public DbSet<OrganizationContractDiscount> OrganizationContractDiscount { get; set; }
        public DbSet<OrganizationCredit> OrganizationCredit { get; set; }
        public DbSet<OrganizationFundAccount> OrganizationFundAccount { get; set; }
        public DbSet<OrganizationGoodReturnRate> OrganizationGoodReturnRate { get; set; }
        public DbSet<OrganizationGoodReturnRatePerQuarter> OrganizationGoodReturnRatePerQuarter { get; set; }
        public DbSet<RetailMonthTaget> RetailMonthTaget { get; set; }
        public DbSet<RetailShift> RetailShift { get; set; }
        public DbSet<RetailShoppingGuide> RetailShoppingGuide { get; set; }
        public DbSet<RetailTactic> RetailTactic { get; set; }
        public DbSet<RetailTacticProStyleMapping> RetailTacticProStyleMapping { get; set; }
        public DbSet<Stock> Stock { get; set; }
        public DbSet<Storage> Storage { get; set; }
        public DbSet<VIPBirthdayConsumption> VIPBirthdayConsumption { get; set; }
        public DbSet<VIPBirthdayTactic> VIPBirthdayTactic { get; set; }
        public DbSet<VIPCard> VIPCard { get; set; }
        public DbSet<VIPCardKindMapping> VIPCardKindMapping { get; set; }
        public DbSet<VIPKind> VIPKind { get; set; }
        public DbSet<VIPPointTrack> VIPPointTrack { get; set; }
        public DbSet<VIPPredepositTrack> VIPPredepositTrack { get; set; }
        public DbSet<VIPUpTactic> VIPUpTactic { get; set; }
        public DbSet<VoucherDeductMoney> VoucherDeductMoney { get; set; }
        public DbSet<VoucherItemKind> VoucherItemKind { get; set; }
        public DbSet<VoucherReceiveMoney> VoucherReceiveMoney { get; set; }
        public DbSet<ViewOrganization> ViewOrganization { get; set; }
        public DbSet<ViewProduct> ViewProduct { get; set; }
        public DbSet<ViewUser> ViewUser { get; set; }
        public DbSet<BillStoringDetails> BillStoringDetails { get; set; }
        public DbSet<ViewProColor> ViewProColor { get; set; }
        public DbSet<ViewProSize> ViewProSize { get; set; }
    }
}
