//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBEncapsulation
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using DbContextExtension;
    using SysProcessModel;
    using Model.Extension;
    
    public partial class SysProcessEntities : AdapDbContext
    {
        public SysProcessEntities()
            : base("SysProcessConstr", "res://*/SysProcess.csdl|res://*/SysProcess.ssdl|res://*/SysProcess.msl")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BusiDataDictionary> BusiDataDictionary { get; set; }
        public DbSet<CertCarriedStandard> CertCarriedStandard { get; set; }
        public DbSet<CertGrade> CertGrade { get; set; }
        public DbSet<Certification> Certification { get; set; }
        public DbSet<CertMateriel> CertMateriel { get; set; }
        public DbSet<CertMaterielKind> CertMaterielKind { get; set; }
        public DbSet<CertSafetyTech> CertSafetyTech { get; set; }
        public DbSet<OrganizationBrand> OrganizationBrand { get; set; }
        public DbSet<OrganizationPriceFloat> OrganizationPriceFloat { get; set; }
        public DbSet<ProBoduan> ProBoduan { get; set; }
        public DbSet<ProBrand> ProBrand { get; set; }
        public DbSet<ProBYQ> ProBYQ { get; set; }
        public DbSet<ProColor> ProColor { get; set; }
        public DbSet<Product> Product { get; set; }
        public DbSet<ProductUniqueCodeMapping> ProductUniqueCodeMapping { get; set; }
        public DbSet<ProName> ProName { get; set; }
        public DbSet<ProSCPicture> ProSCPicture { get; set; }
        public DbSet<ProSize> ProSize { get; set; }
        public DbSet<ProStyle> ProStyle { get; set; }
        public DbSet<ProStyleChange> ProStyleChange { get; set; }
        public DbSet<ProStyleMatching> ProStyleMatching { get; set; }
        public DbSet<ProUnit> ProUnit { get; set; }
        public DbSet<SysApplication> SysApplication { get; set; }
        public DbSet<SysArea> SysArea { get; set; }
        public DbSet<SysCity> SysCity { get; set; }
        public DbSet<SysModule> SysModule { get; set; }
        public DbSet<SysOrganization> SysOrganization { get; set; }
        public DbSet<SysOrganizationType> SysOrganizationType { get; set; }
        public DbSet<SysProvience> SysProvience { get; set; }
        public DbSet<SysRole> SysRole { get; set; }
        public DbSet<SysRoleModule> SysRoleModule { get; set; }
        public DbSet<SysUser> SysUser { get; set; }
        public DbSet<SysUserModule> SysUserModule { get; set; }
        public DbSet<SysUserRole> SysUserRole { get; set; }
        public DbSet<UserBrand> UserBrand { get; set; }
        public DbSet<ViewProduct> ViewProduct { get; set; }
        public DbSet<OrganizationArea> OrganizationArea { get; set; }
        public DbSet<ProQuarter> ProQuarter { get; set; }
    }
}
